# syntax=docker/dockerfile:1

FROM tomcat:latest
COPY files /usr/local/tomcat/webapps
EXPOSE 8080

# 11.0.9-jdk21-temurin-noble, 11.0-jdk21-temurin-noble, 11-jdk21-temurin-noble, jdk21-temurin-noble, 11.0.9-jdk21-temurin, 11.0-jdk21-temurin, 11-jdk21-temurin, jdk21-temurin, 11.0.9-jdk21, 11.0-jdk21, 11-jdk21, jdk21, 11.0.9, 11.0, 11, latest⁠
